name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: debian, ubuntu, android

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./install
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
